namespace: production

apiVersion: v1
kind: Namespace
metadata:
  name: production

patches:
  - target:
      kind: Deployment
      name: course-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
