apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "course-app.name" . }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080